Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Controllers/ErrorCRUDController.cs
using BLL;
using ProyectoV_Vuelos.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;

namespace ProyectoV_Vuelos.Controllers
{
    public class ErrorCRUDController : Controller
    {
        public ActionResult Consulta()
        {
            Errores Error = new Errores();

            try
            {
                if (BuscarErrores() != null)
                {
                    return View(BuscarErrores());
                }
                else
                {
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al mostrar el Index en la Tabla Error: " + ex);
                throw;
            }
        }

        public ActionResult Busqueda(FormCollection item)
        {
            Errores Error = new Errores();
            string fechainicio = item["fechainicio"];
            string fechafinal = item["fechafinal"];

            try
            {
                if (fechainicio == "" && fechafinal == "")
                {
                    return View("~/Views/ErrorCRUD/Consulta.cshtml", BuscarErrores());
                }
                else
                {
                    if (fechainicio != "" && fechafinal != "")
                    {
                        var datos = BuscarErrores().Where(x => x.Fecha >= Convert.ToDateTime(fechainicio) && x.Fecha <= Convert.ToDateTime(fechafinal)).Select(x => x).ToList();
                        return View("~/Views/ErrorCRUD/Consulta.cshtml", datos);
                    }

                    if (fechainicio != "")
                    {
                        var datos = BuscarErrores().Where(x => x.Fecha >= Convert.ToDateTime(fechainicio)).Select(x => x).ToList();
                        return View("~/Views/ErrorCRUD/Consulta.cshtml", datos);
                    }

                    if (fechafinal != "")
                    {
                        var datos = BuscarErrores().Where(x => x.Fecha <= Convert.ToDateTime(fechafinal)).Select(x => x).ToList();
                        return View("~/Views/ErrorCRUD/Consulta.cshtml", datos);
                    }
                }
            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al realizar la busqueda en la Tabla Error: " + ex);
                throw;
            }
            
            return View("~/Views/ErrorCRUD/Consulta.cshtml", BuscarErrores());
        }

        public List<ErrorModel> BuscarErrores()
        {
            Errores Error = new Errores();

            try
            {
                List<ErrorModel> lista =
                Error.SP_Solicitar_Info_Errores().Tables[0].AsEnumerable().Select(e => new ErrorModel
                {
                    ERRID = e.Field<int>("ERRID"),
                    Fecha = e.Field<DateTime>("Fecha"),
                    Mensaje_Error = e.Field<string>("Mensaje_Error"),

                }).ToList();

                return lista;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Valor Null detectado");
                Error.GenerarError(DateTime.Now, "Error al buscar los datos en la Tabla Error: " + ex);
                throw;
            }
        }
    }
}

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/ErrorCRUD/Consulta.cshtml
@model IEnumerable<ProyectoV_Vuelos.Models.ErrorModel>

@{
    ViewBag.Title = "Tropical Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Consulta de Errores</h2></center>

<hr>

<br />

@using (Html.BeginForm("Busqueda", "ErrorCRUD", FormMethod.Post))
{

    <form class="form-group">


        <div class="container">
            <center>
                <div class="row justify-content-md-center">
                    <div class="col col-lg-2">
                        <label class="font-weight-bold">Fecha Inicio</label>
                        @Html.TextBox("fechainicio", "", new { @class = "form-control" })
                    </div>
                    <div class="col col-lg-2">
                        <label class="font-weight-bold">Fecha Final</label>
                        @Html.TextBox("fechafinal", "", new { @class = "form-control" })
                    </div>
                </div>
            </center>
        </div>

        <br />

        <center>
            <button type="submit" class="btn btn-default border">Buscar</button>
        </center>

    </form>
}

<br />
<br />

<table class="table">
    <tr>
        <th>
          ID de Error
        </th>
        <th>
          Fecha
        </th>
        <th>
          Mensaje de Error
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ERRID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mensaje_Error)
                </td>
            </tr>
        }
    }
</table>

<br></br>

<center>

    <a class="btn btn-default border" @Html.ActionLink("Regresar", "Index", "Home", new { area = "" }, null)</a>
    <a class="btn btn-default border" @Html.ActionLink("Mostrar Todos", "Consulta", "ErrorCRUD", new { area = "" }, null)</a>

</center>