Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Controllers/AerolineaCRUDController.cs
using BLL;
using ProyectoV_Vuelos.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;

namespace ProyectoV_Vuelos.Controllers
{
    public class AerolineaCRUDController : Controller
    {
        public ActionResult Index()
        {
            Errores Error = new Errores();

            try
            {
                if (BuscarAerolineas() != null)
                {
                    return View(BuscarAerolineas());
                }
                else
                {
                    throw new Exception();
                }

            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al mostrar el Index en la Tabla Aerolínea: " + ex);
                throw;
            }
        }

        public ActionResult Consulta()
        {
            Errores Error = new Errores();

            try
            {
                if (BuscarAerolineas() != null)
                {
                    return View(BuscarAerolineas());
                }
                else
                {
                    throw new Exception();
                }

            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al mostrar las Consultas en la Tabla Aerolínea: " + ex);
                throw;
            }
        }

        public ActionResult Busqueda(FormCollection item)
        {
            Errores Error = new Errores();

            try
            {
                Pais pais = new Pais();
                Aerolineas Aerolinea = new Aerolineas();
                string Nombre = item["nombre"];
                var PAISID = pais.SP_Solicitar_Filtro_Pais(Nombre).PAISID;
                var datos = BuscarAerolineas().Where(x => x.Aerol_Pais == PAISID).Select(x => x).ToList();

                return View("~/Views/AerolineaCRUD/Consulta.cshtml", datos);
            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al realizar la busqueda en la Tabla Aerolínea: " + ex);
                throw;
            }
        }

        public List<AerolineasModel> BuscarAerolineas()
        {
            Errores Error = new Errores();

            try
            {
                Aerolineas Aerolineas = new Aerolineas();
                List<AerolineasModel> lista =
                Aerolineas.SP_Solicitar_Info_Aerolineas().Tables[0].AsEnumerable().Select(e => new AerolineasModel
                {
                    ALNID = e.Field<int>("ALNID"),
                    Aerol_Pais = e.Field<int>("Aerol_Pais"),
                    Consec_Aerol = e.Field<int>("Consec_Aerol"),
                    Codigo = e.Field<string>("Codigo"),
                    Nombre = e.Field<string>("Nombre"),
                    Imagen = e.Field<string>("Imagen"),

                }).ToList();

                return lista;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Valor Null detectado");
                Error.GenerarError(DateTime.Now, "Error al buscar las aerolíneas en la Tabla Aerolínea: " + ex);
                throw;
            }
        }

        public ActionResult Generar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Generar(AerolineasModel a)
        {
            Aerolineas ALN = new Aerolineas();
            Bitacoras BTC = new Bitacoras();
            Errores Error = new Errores();

            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                ALN.GenerarAerolinea(a.Aerol_Pais, a.Consec_Aerol, a.Codigo, a.Nombre, a.Imagen);
                BTC.GenerarBitacora(a.Consec_Aerol, 1, 1, DateTime.Now, "Agregar", "Inserción de una nueva Aerolínea",
                    a.Codigo, a.Nombre, a.Imagen, 0, "", "", "", "", "", DateTime.Now, "", 0);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al Generar Aerolinea", ex);
                Error.GenerarError(DateTime.Now, "Error al generar una nueva aerolínea en la Tabla Aerolínea: " + ex);
                return View();
            }

        }

        public ActionResult Actualizar(int id)
        {
            Errores Error = new Errores();

            try
            {
                if (BuscarAerolineas().Where(e => e.ALNID == id).First() != null)
                {
                    return View(BuscarAerolineas().Where(e => e.ALNID == id).First());
                }
                else
                {
                    throw new Exception();
                }

            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al buscar una aerolínea en la Tabla Aerolínea: " + ex);
                throw;
            }
        }

        [HttpPost]
        public ActionResult Actualizar(AerolineasModel a)
        {
            Aerolineas ALN = new Aerolineas();
            Bitacoras BTC = new Bitacoras();
            Errores Error = new Errores();

            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                ALN.ActualizarAerolinea(a.ALNID, a.Aerol_Pais, a.Consec_Aerol, a.Codigo, a.Nombre, a.Imagen);
                BTC.GenerarBitacora(a.Consec_Aerol, 1, 2, DateTime.Now, "Modificar", "Modificación de una Aerolínea",
                    a.Codigo, a.Nombre, a.Imagen, 0, "", "", "", "", "", DateTime.Now, "", 0);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al Actualizar Aerolinea", ex);
                Error.GenerarError(DateTime.Now, "Error al actualizar una aerolínea en la Tabla Aerolínea: " + ex);
                return View();
            }

        }

        public ActionResult Eliminar(int id)
        {

            Aerolineas ALN = new Aerolineas();
            Bitacoras BTC = new Bitacoras();
            Errores Error = new Errores();

            try
            {
                BTC.GenerarBitacora(ALN.SP_Solicitar_Consec_Aerolinea(id).Consec_Aerol, 1, 3, DateTime.Now, "Eliminar", "Eliminación de una Aerolínea",
                "", "", "", 0, "", "", "", "", "", DateTime.Now, "", 0);
                ALN.EliminarAerolinea(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al eliminar una aerolínea en la Tabla Aerolínea: " + ex);
                throw;
            }
        }
    }
}

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/AerolineaCRUD/Actualizar.cshtml
@model ProyectoV_Vuelos.Models.AerolineasModel

@{
    ViewBag.Title = "Tropical Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <center>
        <h3 class="text-center">Aerolineas</h3>
        <hr />

        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ALNID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

        <div class="form-group">
            <h5 class="text-center">Pais de Aereolinea</h5>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aerol_Pais, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aerol_Pais, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <h5 class="text-center">Consecutivo de Aereolinea</h5>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Consec_Aerol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Consec_Aerol, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <h5 class="text-center">Codigo</h5>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <h5 class="text-center">Nombre</h5>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <h5 class="text-center">Logo</h5>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default border" />
            </div>

            <br />

            <div class="col-md-offset-2 col-md-10">
                <a class="btn btn-default border"
                   @Html.ActionLink("Cancelar", "Index")
            </div>
        </div>
        </center>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/AerolineaCRUD/Consulta.cshtml
@model IEnumerable<ProyectoV_Vuelos.Models.AerolineasModel>

@{
    ViewBag.Title = "Tropical Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Consulta de Aereolineas</h2></center>

<hr>

<br />


@using (Html.BeginForm("Busqueda", "AerolineaCRUD", FormMethod.Post))
{
    <form class="form-group">
        <center>
            <div>
                <div>
                    <div>
                        <div class="form-group mb-1">
                            <label class="font-weight-bold">Nombre del País</label>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.TextBox("nombre", "", new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-default border">Buscar</button>

        </center>
    </form>
}

<br />


<table class="table">
    <center>
        <tr>
            <th>
            Codigo
            </th>
            <th>
             Nombre
            </th>
            <th>
            Logo
            </th>
            <th></th>
        </tr>


        <br />

        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        <img src="@Html.DisplayFor(modelItem => item.Imagen)" width="70px" height="50px" alt="Aereolinea" />
                    </td>
                </tr>
            }
        }
    </center>
</table>



<br></br>

<center>

    <a class="btn btn-default border" @Html.ActionLink("Regresar", "Index", "Home", new { area = "" }, null)</a>
    <a class="btn btn-default border" @Html.ActionLink("Mostrar Todos", "Consulta", "AerolineaCRUD", new { area = "" }, null)</a>

</center>

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/AerolineaCRUD/Generar.cshtml
@model ProyectoV_Vuelos.Models.AerolineasModel

@{
    ViewBag.Title = "Tropical Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <center>
        <div class="form-horizontal">
            <h3 class="text-center">Aerolineas</h3>
            <hr />

            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <h5 class="text-center">Pais de Aerolinea</h5>

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Aerol_Pais, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Aerol_Pais, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <h5 class="text-center">Consecutivo de Aerolinea</h5>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Consec_Aerol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Consec_Aerol, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <h5 class="text-center">Codigo</h5>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <h5 class="text-center">Nombre</h5>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <h5 class="text-center">Logo</h5>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Generar" class="btn btn-default border" />
                </div>

                <br />

                <div class="col-md-offset-2 col-md-10">
                    <a class="btn btn-default border"
                       @Html.ActionLink("Cancelar", "Index")
                </div>
            </div>
        </div>
    </center>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/AerolineaCRUD/Index.cshtml
@model IEnumerable<ProyectoV_Vuelos.Models.AerolineasModel>

@{
    ViewBag.Title = "Tropical Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Aerolineas</h2></center>
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.Imagen)" width="70px" height="50px" alt="Logo">
                </td>
                <td>
                    @Html.ActionLink("Editar", "Actualizar", new { id = item.ALNID }, null) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.ALNID }, new { @Class = "MEliminar" })
                </td>
            </tr>
        }
    }

</table>

<br />

<center>

    <a class="btn btn-default border" @Html.ActionLink("Generar ", "Generar")</a>

    <a class="btn btn-default border" @Html.ActionLink("Regresar", "Index", "Home", new { area = "" }, null)</a>

</center>

@section scripts{

    <script>
        $(".MEliminar").click(function (event) {
            if (!confirm('¿Esta seguro de eliminar la Aerolinea?')) {
                event.preventDefault();
            }
        });
    </script>
}