Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Controllers/PaisCRUDController.cs
using BLL;
using ProyectoV_Vuelos.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;

namespace ProyectoV_Vuelos.Controllers
{
    public class PaisCRUDController : Controller
    {

        public ActionResult Index()
        {
            Errores Error = new Errores();

            try
            {
                if (BuscarPaises() != null)
                {
                    return View(BuscarPaises());
                }
                else
                {
                    throw new Exception();
                }

            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al mostrar el Index en la Tabla País: " + ex);
                throw;
            }
        }

        public List<PaisModel> BuscarPaises()
        {
            Errores Error = new Errores();

            try
            {
                Pais Paises = new Pais();
                List<PaisModel> lista =
                Paises.SP_Solicitar_Info_Paises().Tables[0].AsEnumerable().Select(e => new PaisModel
                {
                    PAISID = e.Field<int>("PAISID"),
                    Consec_Pais = e.Field<int>("Consec_Pais"),
                    CodPais = e.Field<string>("CodPais"),
                    Nombre = e.Field<string>("Nombre"),
                    Imagen = e.Field<string>("Imagen"),


                }).ToList();

                return lista;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Valor Null detectado");
                Error.GenerarError(DateTime.Now, "Error al buscar los países en la Tabla País: " + ex);
                throw;
            }
        }

        public ActionResult Generar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Generar(PaisModel a)
        {
            Pais PAIS = new Pais();
            Bitacoras BTC = new Bitacoras();
            Errores Error = new Errores();

            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                PAIS.Generar(a.Consec_Pais, a.CodPais, a.Nombre, a.Imagen);
                BTC.GenerarBitacora(a.Consec_Pais, 1, 1, DateTime.Now, "Agregar", "Inserción de un nuevo País", 
                    a.CodPais, a.Nombre, a.Imagen, 0, "", "", "", "", "", DateTime.Now, "", 0);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al Generar el Pais", ex);
                Error.GenerarError(DateTime.Now, "Error al generar un nuevo país en la Tabla País: " + ex);
                return View();
            }

        }

        public ActionResult Actualizar(int id)
        {
            Errores Error = new Errores();

            try
            {
                if (BuscarPaises().Where(e => e.PAISID == id).First() != null)
                {
                    return View(BuscarPaises().Where(e => e.PAISID == id).First());
                }
                else
                {
                    throw new Exception();
                }

            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al buscar un país en la Tabla País: " + ex);
                throw;
            }
        }

        [HttpPost]
        public ActionResult Actualizar(PaisModel a)
        {
            Pais PAIS = new Pais();
            Bitacoras BTC = new Bitacoras();
            Errores Error = new Errores();

            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                PAIS.Actualizar(a.PAISID, a.Consec_Pais, a.CodPais, a.Nombre, a.Imagen);
                BTC.GenerarBitacora(a.Consec_Pais, 1, 2, DateTime.Now, "Modificar", "Modificación de un País",
                    a.CodPais, a.Nombre, a.Imagen, 0, "", "", "", "", "", DateTime.Now, "", 0);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al actualizar el Pais", ex);
                Error.GenerarError(DateTime.Now, "Error al actualizar un país en la Tabla País: " + ex);
                return View();
            }

        }

        public ActionResult Eliminar(int id)
        {

            Pais PAIS = new Pais();
            Bitacoras BTC = new Bitacoras();
            Errores Error = new Errores();

            try
            {
                BTC.GenerarBitacora(PAIS.SP_Solicitar_Consec_Pais(id).Consec_Pais, 1, 3, DateTime.Now, "Eliminar", "Eliminación de un País",
                "", "", "", 0, "", "", "", "", "", DateTime.Now, "", 0);
                PAIS.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Error.GenerarError(DateTime.Now, "Error al eliminar un país en la Tabla País: " + ex);
                throw;
            }
        }
    }
}

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Logo/linea aeria blanco-04.ico" rel="shortcut icon" type="image/x-icon" />
    @RenderSection("Css", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Header.css" rel="stylesheet" />
</head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<header id="header" >

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark  scrolling-navbar" style="background-color: #8C7811">
        <img src="~/Content/Logo/linea aeria blanco-04.png" alt="Icono" / width="100px" height="50px">
        <a class="navbar-brand" href="@Url.Action("Index","Home")"><strong>Tropical Airlines</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">

                    <div class="dropdown">
                        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Seguridad
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="@Url.Action("Generar","SeguridadCRUD")">Crear Usuarios</a>
                            <a class="dropdown-item" href="@Url.Action("Index","SeguridadCRUD")">Asignar Roles</a>
                            <a class="dropdown-item" href="@Url.Action("Actualizarcontrasena","SeguridadCRUD")">Cambiar Contraseña</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Administracion
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="@Url.Action("Index","ConsecutivoCRUD")">Consecutivos »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","AerolineaCRUD")">Aereolineas »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","AeropuertoCRUD")">Aereopuerto »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","PaisCRUD")">Pais »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","VueloCRUD/IndexLlegada")">Vuelos de Llegada »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","VueloCRUD/IndexSalida")">Vuelos de Salida »</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Consultas
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="@Url.Action("Index","BitacoraCRUD/Consulta")">Bitacora »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","ErrorCRUD/Consulta")">Errores »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","AerolineaCRUD/Consulta")">Aerolinea »</a>
                            <a class="dropdown-item" href="@Url.Action("Index","AeropuertoCRUD/Consulta")">Aeropuerto »</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Opciones
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="@Url.Action("Index","Help")">API  »</a>
                            <a class="dropdown-item" href="@Url.Action("Actualizarcontrasena","SeguridadCRUD")">Cambiar Contraseña »</a>
                            <a class="dropdown-item" href="@Url.Action("Login","SeguridadCRUD")">Cerrar Sesion »</a>
                        </div>
                    </div>
                </li>

                <right>
                    <li class="nav-item">
                        <div class="container">
                            <button class="btn text-white disabled" type="button" id="User" ia-haspopup="true" aria-expanded="false">
                                Bienvenido Usuario
                            </button>
                        </div>
                    </li>
                </right>
            </ul>
        </div>
    </nav>

    <div class="view intro-2" style="">
        <div class="full-bg-img">
            <div class="mask rgba-purple-light flex-center">
                <div class="container text-center white-text wow fadeInUp">
                </div>
            </div>
        </div>
    </div>

</header>

<br />
<br />
<br />

<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <footer class="text-white" style="background-color: #8C7811">
        <div class="container">
            <br />
            <br />
            <div class="row ">
                <div class="col-md-5">
                    <br />
                    <p></p>
                    <br />
                    <center>
                        <h4><img src="~/Content/Logo/linea aeria blanco-04.png" alt="Icono" / width="150px" height="100px"> <a></a> <b> Tropical Airlines </b></h4>
                    </center>
                    <br />
                    <p></p>
                    <br />
                </div>

                <div class="col-md-2">
                    <h4><b>Compañia</b></h4>
                    <br />
                    <p><a href="#" class="text-white">Acerca de nosotros</a></p>
                    <p><a href="#" class="text-white">Novedades</a></p>
                    <p><a href="#" class="text-white">Asociaciones</a></p>
                    <br />
                </div>

                <div class="col-md-2">
                    <h4><b>Soporte</b></h4>
                    <br />
                    <p><a href="#" class="text-white">Ayuda</a></p>
                    <p><a href="#" class="text-white">Contactenos</a></p>
                </div>

                <div class="col-md-3">
                    <br />
                    <p></p>
                    <br />
                    <center>
                        <h4><img src="~/Content/icons/circle-cropped.png" alt="Icono" / width="100px" height="100px"></h4>
                    </center>
                </div>
            </div>
        </div>
    </footer>

</body>

<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
<script src="~/Scripts/popper.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

@RenderSection("Scripts", required: false)

</html>

Code/ProyectoV-Vuelos/ProyectoV-Vuelos/Views/Shared/_LayoutNL.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Logo/linea aeria blanco-04.ico" rel="shortcut icon" type="image/x-icon" />

    @RenderSection("Css", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Header.css" rel="stylesheet" />
</head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<header id="header">

    <nav class="navbar fixed-top navbar-light" style="background-color: #8C7811" >
        <img src="~/Content/Logo/linea aeria blanco-04.png" alt="Icono" / width="100px" height="50px">
        <a class="navbar-brand text-white" href="@Url.Action("Login","SeguridadCRUD")"><strong>Tropical Airlines</strong></a>
        <button class="btn"> <a class="text-white" href="@Url.Action("Login","SeguridadCRUD")"><strong>Iniciar Sesion</strong></a></button>
    </nav>

    <div class="view intro-2" style="">
        <div class="full-bg-img">
            <div class="mask rgba-purple-light flex-center">
                <div class="container text-center white-text wow fadeInUp">
                </div>
            </div>
        </div>
    </div>

</header>

<br />
<br />
<br />

<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <footer class="text-white" style="background-color: #8C7811">
        <div class="container">
            <br />
            <br />
            <div class="row ">
                <div class="col-md-5">
                    <br />
                    <p></p>
                    <br />
                    <center>
                        <h4><img src="~/Content/Logo/linea aeria blanco-04.png" alt="Icono" / width="150px" height="100px"> <a></a> <b> Tropical Airlines </b></h4>
                    </center>
                    <br />
                    <p></p>
                    <br />
                </div>

                <div class="col-md-2">
                    <h4><b>Compañia</b></h4>
                    <br />
                    <p><a href="#" class="text-white">Acerca de nosotros</a></p>
                    <p><a href="#" class="text-white">Novedades</a></p>
                    <p><a href="#" class="text-white">Asociaciones</a></p>
                    <br />
                </div>

                <div class="col-md-2">
                    <h4><b>Soporte</b></h4>
                    <br />
                    <p><a href="#" class="text-white">Ayuda</a></p>
                    <p><a href="#" class="text-white">Contactenos</a></p>
                </div>

                <div class="col-md-3">
                    <br />
                    <p></p>
                    <br />
                    <center>
                        <h4><img src="~/Content/icons/circle-cropped.png" alt="Icono" / width="100px" height="100px"></h4>
                    </center>
                </div>
            </div>
        </div>
    </footer>
</body>

<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
<script src="~/Scripts/popper.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

@RenderSection("Scripts", required: false)

</html>